server:
  port: 7001


spring:
  datasource:
    username:
    password:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:coder-db.sqlite
  flyway:
    baseline-on-migrate: false
    check-location: false
    enabled: false
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: "classpath*:com/chenx/**/mapper/sql/*.xml"